const translations = {
    "en": {"pageTitle": "Free Foot Traffic Estimator | Plan Your New Business Location", "metaDescription": "Estimate foot traffic for your business location using our free interactive map.", "headerTitle": "Estimate Foot Traffic for Your Business. For FREE", "headerSubtitle": "Analyze foot traffic and find the best location for your store, restaurant, or office.", "loadingText": "Calculating Foot Traffic in the Area...", "mapPlaceholder": "Loading map...", "peoplePassingBy": "People passing by"},
    "zh": {"pageTitle": "免费人流量估算器 | 规划您的新商铺位置", "metaDescription": "使用我们的免费互动地图估算您的商业位置人流量。", "headerTitle": "估算您的商业人流量。免费！", "headerSubtitle": "分析人流量并找到最佳商店、餐厅或办公地点。", "loadingText": "正在计算该地区的人流量...", "mapPlaceholder": "加载地图...", "peoplePassingBy": "路过的人"},
    "es": {"pageTitle": "Estimador de Tráfico Peatonal Gratis | Planifique su Ubicación Comercial", "metaDescription": "Estime el tráfico peatonal para la ubicación de su negocio con nuestro mapa interactivo gratuito.", "headerTitle": "Estime el tráfico peatonal para su negocio. GRATIS", "headerSubtitle": "Analice el tráfico peatonal y encuentre la mejor ubicación para su tienda, restaurante u oficina.", "loadingText": "Calculando el tráfico peatonal en el área...", "mapPlaceholder": "Cargando mapa...", "peoplePassingBy": "Personas pasando"},
    "ar": {"pageTitle": "مقدر حركة المشاة المجاني | خطط لموقع عملك الجديد", "metaDescription": "قم بتقدير حركة المشاة لموقع عملك باستخدام خريطتنا التفاعلية المجانية.", "headerTitle": "قم بتقدير حركة المشاة لعملك. مجانًا!", "headerSubtitle": "قم بتحليل حركة المشاة واعثر على أفضل موقع لمتجرك أو مطعمك أو مكتبك.", "loadingText": "جاري حساب حركة المشاة في المنطقة...", "mapPlaceholder": "تحميل الخريطة...", "peoplePassingBy": "الأشخاص المارون"},
    "id": {"pageTitle": "Perkiraan Lalu Lintas Pejalan Kaki Gratis | Rencanakan Lokasi Bisnis Baru Anda", "metaDescription": "Perkirakan lalu lintas pejalan kaki untuk lokasi bisnis Anda menggunakan peta interaktif gratis kami.", "headerTitle": "Perkirakan Lalu Lintas Pejalan Kaki untuk Bisnis Anda. GRATIS!", "headerSubtitle": "Analisis lalu lintas pejalan kaki dan temukan lokasi terbaik untuk toko, restoran, atau kantor Anda.", "loadingText": "Menghitung lalu lintas pejalan kaki di area ini...", "mapPlaceholder": "Memuat peta...", "peoplePassingBy": "Orang yang lewat"},
    "ms": {"pageTitle": "Anggaran Lalu Lintas Pejalan Kaki Percuma | Rancang Lokasi Perniagaan Baru Anda", "metaDescription": "Anggarkan lalu lintas pejalan kaki untuk lokasi perniagaan anda dengan peta interaktif percuma kami.", "headerTitle": "Anggarkan Lalu Lintas Pejalan Kaki untuk Perniagaan Anda. PERCUMA!", "headerSubtitle": "Analisis lalu lintas pejalan kaki dan cari lokasi terbaik untuk kedai, restoran, atau pejabat anda.", "loadingText": "Mengira lalu lintas pejalan kaki di kawasan ini...", "mapPlaceholder": "Memuatkan peta...", "peoplePassingBy": "Orang yang lalu"},
    "pt": {"pageTitle": "Estimador de Tráfego de Pedestres Grátis | Planeje Sua Nova Localização Comercial", "metaDescription": "Estime o tráfego de pedestres para o local do seu negócio usando nosso mapa interativo gratuito.", "headerTitle": "Estime o tráfego de pedestres para o seu negócio. GRÁTIS!", "headerSubtitle": "Analise o tráfego de pedestres e encontre o melhor local para sua loja, restaurante ou escritório.", "loadingText": "Calculando o tráfego de pedestres na área...", "mapPlaceholder": "Carregando mapa...", "peoplePassingBy": "Pessoas passando"},
    "fr": {"pageTitle": "Estimateur de Trafic Piéton Gratuit | Planifiez Votre Nouvel Emplacement Commercial", "metaDescription": "Estimez le trafic piéton pour l'emplacement de votre entreprise avec notre carte interactive gratuite.", "headerTitle": "Estimez le trafic piéton pour votre entreprise. GRATUITEMENT", "headerSubtitle": "Analysez le trafic piéton et trouvez le meilleur emplacement pour votre magasin, restaurant ou bureau.", "loadingText": "Calcul du trafic piéton dans la zone...", "mapPlaceholder": "Chargement de la carte...", "peoplePassingBy": "Personnes qui passent"},
    "ja": {"pageTitle": "無料の歩行者交通量推定ツール | 新しいビジネスの場所を計画", "metaDescription": "無料のインタラクティブマップを使用して、ビジネスの立地の歩行者数を推定します。", "headerTitle": "ビジネスの歩行者数を推定しましょう。無料！", "headerSubtitle": "歩行者の流れを分析し、店舗、レストラン、オフィスに最適な場所を見つけましょう。", "loadingText": "エリアの歩行者交通量を計算中...", "mapPlaceholder": "マップを読み込み中...", "peoplePassingBy": "通り過ぎる人々"},
    "ru": {"pageTitle": "Бесплатный Оценщик Потока Людей | Планируйте Ваше Бизнес-Место", "metaDescription": "Оцените поток пешеходов для вашего бизнеса с помощью нашей бесплатной интерактивной карты.", "headerTitle": "Оцените поток людей для вашего бизнеса. БЕСПЛАТНО", "headerSubtitle": "Анализируйте поток пешеходов и находите лучшее место для вашего магазина, ресторана или офиса.", "loadingText": "Рассчитываем поток людей в области...", "mapPlaceholder": "Загрузка карты...", "peoplePassingBy": "Проходящие люди"},
    "de": {"pageTitle": "Kostenloser Fußgängertraffic-Schätzer | Planen Sie Ihren neuen Geschäftsstandort", "metaDescription": "Schätzen Sie den Fußgängertraffic für Ihren Geschäftsstandort mit unserer kostenlosen interaktiven Karte.", "headerTitle": "Schätzen Sie den Fußgängertraffic für Ihr Geschäft. KOSTENLOS", "headerSubtitle": "Analysieren Sie den Fußgängertraffic und finden Sie den besten Standort für Ihr Geschäft, Restaurant oder Büro.", "loadingText": "Berechnung des Fußgängertraffics im Gebiet...", "mapPlaceholder": "Karte wird geladen...", "peoplePassingBy": "Vorbeigehende Menschen"},
    "bn": {"pageTitle": "বিনামূল্যে পথচারী ট্র্যাফিক অনুমানকারী | আপনার নতুন ব্যবসার স্থান পরিকল্পনা করুন", "metaDescription": "আমাদের বিনামূল্যে ইন্টারেক্টিভ মানচিত্র ব্যবহার করে আপনার ব্যবসার স্থানের পথচারী ট্র্যাফিক অনুমান করুন।", "headerTitle": "আপনার ব্যবসার জন্য পথচারী ট্র্যাফিক অনুমান করুন। বিনামূল্যে!", "headerSubtitle": "পথচারী ট্র্যাফিক বিশ্লেষণ করুন এবং আপনার দোকান, রেস্তোরাঁ বা অফিসের জন্য সেরা স্থান খুঁজুন।", "loadingText": "এলাকায় পথচারী ট্র্যাফিক গণনা করা হচ্ছে...", "mapPlaceholder": "মানচিত্র লোড হচ্ছে...", "peoplePassingBy": "পথচারীরা"},
    "hi": {"pageTitle": "मुफ्त पैदल यातायात अनुमानक | अपने नए व्यवसाय स्थान की योजना बनाएं", "metaDescription": "हमारे मुफ्त इंटरैक्टिव नक्शे का उपयोग करके अपने व्यवसाय स्थान के लिए पैदल यातायात का अनुमान लगाएं।", "headerTitle": "अपने व्यवसाय के लिए पैदल यातायात का अनुमान लगाएं। मुफ्त में!", "headerSubtitle": "पैदल यातायात का विश्लेषण करें और अपनी दुकान, रेस्तरां या कार्यालय के लिए सबसे अच्छा स्थान खोजें।", "loadingText": "क्षेत्र में पैदल यातायात की गणना हो रही है...", "mapPlaceholder": "नक्शा लोड हो रहा है...", "peoplePassingBy": "गुजरने वाले लोग"},
    "ko": {"pageTitle": "무료 보행자 교통 추정기 | 새로운 비즈니스 위치 계획", "metaDescription": "무료 인터랙티브 지도를 사용하여 비즈니스 위치의 보행자 교통을 추정하세요.", "headerTitle": "비즈니스의 보행자 교통을 추정하세요. 무료로!", "headerSubtitle": "보행자 교통을 분석하고 상점, 레스토랑 또는 사무실에 가장 적합한 위치를 찾으세요.", "loadingText": "지역 내 보행자 교통 계산 중...", "mapPlaceholder": "지도 로딩 중...", "peoplePassingBy": "지나가는 사람들"},
    "it": {"pageTitle": "Stimatore di Traffico Pedonale Gratuito | Pianifica la Tua Nuova Posizione Commerciale", "metaDescription": "Stima il traffico pedonale per la posizione della tua attività con la nostra mappa interattiva gratuita.", "headerTitle": "Stima il traffico pedonale per la tua attività. GRATIS", "headerSubtitle": "Analizza il traffico pedonale e trova la posizione migliore per il tuo negozio, ristorante o ufficio.", "loadingText": "Calcolo del traffico pedonale nell'area...", "mapPlaceholder": "Caricamento mappa...", "peoplePassingBy": "Persone che passano"},
    "tr": {"pageTitle": "Ücretsiz Yaya Trafiği Tahmin Aracı | Yeni İş Yerinizin Konumunu Planlayın", "metaDescription": "Ücretsiz interaktif haritamızı kullanarak iş yerinizin konumu için yaya trafiğini tahmin edin.", "headerTitle": "İşiniz için yaya trafiğini tahmin edin. ÜCRETSİZ!", "headerSubtitle": "Yaya trafiğini analiz edin ve mağazanız, restoranınız veya ofisiniz için en iyi konumu bulun.", "loadingText": "Bölgedeki yaya trafiği hesaplanıyor...", "mapPlaceholder": "Harita yükleniyor...", "peoplePassingBy": "Geçen insanlar"},
    "vi": {"pageTitle": "Công cụ Ước lượng Lưu lượng Người đi bộ Miễn phí | Lập kế hoạch Địa điểm Kinh doanh Mới của Bạn", "metaDescription": "Ước lượng lưu lượng người đi bộ cho địa điểm kinh doanh của bạn bằng bản đồ tương tác miễn phí của chúng tôi.", "headerTitle": "Ước lượng Lưu lượng Người đi bộ cho Doanh nghiệp của Bạn. MIỄN PHÍ!", "headerSubtitle": "Phân tích lưu lượng người đi bộ và tìm vị trí tốt nhất cho cửa hàng, nhà hàng hoặc văn phòng của bạn.", "loadingText": "Đang tính toán lưu lượng người đi bộ trong khu vực...", "mapPlaceholder": "Đang tải bản đồ...", "peoplePassingBy": "Người qua lại"},
    "fa": {"pageTitle": "ابزار تخمین رایگان ترافیک عابران پیاده | مکان جدید کسب‌وکار خود را برنامه‌ریزی کنید", "metaDescription": "با استفاده از نقشه تعاملی رایگان ما، ترافیک عابران پیاده را برای مکان کسب‌وکارتان تخمین بزنید.", "headerTitle": "ترافیک عابران پیاده را برای کسب‌وکارتان تخمین بزنید. رایگان!", "headerSubtitle": "ترافیک عابران پیاده را تحلیل کنید و بهترین مکان را برای فروشگاه، رستوران یا دفتر خود پیدا کنید.", "loadingText": "در حال محاسبه ترافیک عابران پیاده در منطقه...", "mapPlaceholder": "در حال بارگذاری نقشه...", "peoplePassingBy": "افراد عبوری"},
    "th": {"pageTitle": "เครื่องมือประเมินการจราจรเท้าเดินฟรี | วางแผนสถานที่ตั้งธุรกิจใหม่ของคุณ", "metaDescription": "ประเมินการจราจรเท้าเดินสำหรับสถานที่ตั้งธุรกิจของคุณโดยใช้แผนที่แบบโต้ตอบฟรีของเรา", "headerTitle": "ประเมินการจราจรเท้าเดินสำหรับธุรกิจของคุณ ฟรี!", "headerSubtitle": "วิเคราะห์การจราจรเท้าเดินและค้นหาสถานที่ที่ดีที่สุดสำหรับร้านค้า ร้านอาหาร หรือสำนักงานของคุณ", "loadingText": "กำลังคำนวณการจราจรเท้าเดินในพื้นที่...", "mapPlaceholder": "กำลังโหลดแผนที่...", "peoplePassingBy": "คนที่ผ่านไปมา"},
    "ur": {"pageTitle": "مفت پیدل ٹریفک تخمینہ لگانے والا | اپنے نئے کاروبار کے مقام کی منصوبہ بندی کریں", "metaDescription": "ہمارے مفت انٹرایکٹو نقشے کا استعمال کرتے ہوئے اپنے کاروبار کے مقام کے لئے پیدل ٹریفک کا تخمینہ لگائیں۔", "headerTitle": "اپنے کاروبار کے لئے پیدل ٹریفک کا تخمینہ لگائیں۔ مفت میں!", "headerSubtitle": "پیدل ٹریفک کا تجزیہ کریں اور اپنی دکان، ریستوراں یا دفتر کے لئے بہترین مقام تلاش کریں۔", "loadingText": "علاقے میں پیدل ٹریفک کا حساب لگایا جا رہا ہے...", "mapPlaceholder": "نقشہ لوڈ ہو رہا ہے...", "peoplePassingBy": "گزرنے والے لوگ"},
    "pl": {"pageTitle": "Darmowy Estymator Ruchu Pieszego | Zaplanuj Nową Lokalizację Biznesową", "metaDescription": "Oszacuj ruch pieszy dla lokalizacji Twojego biznesu za pomocą naszej darmowej interaktywnej mapy.", "headerTitle": "Oszacuj ruch pieszy dla Twojego biznesu. ZA DARMO", "headerSubtitle": "Analizuj ruch pieszy i znajdź najlepszą lokalizację dla swojego sklepu, restauracji lub biura.", "loadingText": "Obliczanie ruchu pieszego w okolicy...", "mapPlaceholder": "Ładowanie mapy...", "peoplePassingBy": "Przechodzący ludzie"},
    "nl": {"pageTitle": "Gratis Voetgangersverkeer Schatter | Plan Uw Nieuwe Bedrijfslocatie", "metaDescription": "Schat het voetgangersverkeer voor uw bedrijfslocatie met onze gratis interactieve kaart.", "headerTitle": "Schatten van voetgangersverkeer voor uw bedrijf. GRATIS", "headerSubtitle": "Analyseer het voetgangersverkeer en vind de beste locatie voor uw winkel, restaurant of kantoor.", "loadingText": "Berekening van voetgangersverkeer in het gebied...", "mapPlaceholder": "Kaart laden...", "peoplePassingBy": "Voorbijgangers"},
    "fil": {"pageTitle": "Libreng Estimador ng Trapikong Pang-paa | Planuhin ang Bagong Lokasyon ng Iyong Negosyo", "metaDescription": "Estimahin ang trapikong pang-paa para sa lokasyon ng iyong negosyo gamit ang aming libreng interactive na mapa.", "headerTitle": "Estimahin ang Trapikong Pang-paa para sa Iyong Negosyo. LIBRE!", "headerSubtitle": "Suriin ang trapikong pang-paa at hanapin ang pinakamahusay na lokasyon para sa iyong tindahan, restawran, o opisina.", "loadingText": "Kino-kompyut ang trapikong pang-paa sa lugar...", "mapPlaceholder": "Nilo-load ang mapa...", "peoplePassingBy": "Mga dumadaan na tao"},
    "ro": {"pageTitle": "Estimator Gratuit al Traficului Pietonal | Planificați Noua Locație a Afacerii", "metaDescription": "Estimați traficul pietonal pentru locația afacerii dvs. folosind harta noastră interactivă gratuită.", "headerTitle": "Estimați traficul pietonal pentru afacerea dvs. GRATUIT", "headerSubtitle": "Analizați traficul pietonal și găsiți cea mai bună locație pentru magazinul, restaurantul sau biroul dvs.", "loadingText": "Se calculează traficul pietonal în zonă...", "mapPlaceholder": "Se încarcă harta...", "peoplePassingBy": "Persoane care trec"},
    "uk": {"pageTitle": "Безкоштовний оцінювач пішохідного трафіку | Плануйте своє бізнес-місце", "metaDescription": "Оцініть пішохідний трафік для вашого бізнесу за допомогою нашої безкоштовної інтерактивної карти.", "headerTitle": "Оцініть пішохідний трафік для вашого бізнесу. БЕЗКОШТОВНО", "headerSubtitle": "Аналізуйте пішохідний трафік і знаходьте найкраще місце для магазину, ресторану чи офісу.", "loadingText": "Обчислення пішохідного трафіку в цій області...", "mapPlaceholder": "Завантаження карти...", "peoplePassingBy": "Люди, що проходять"},
    "el": {"pageTitle": "Δωρεάν Εκτιμητής Κυκλοφορίας Πεζών | Σχεδιάστε τη Νέα Τοποθεσία της Επιχείρησής σας", "metaDescription": "Εκτιμήστε την κυκλοφορία πεζών για την τοποθεσία της επιχείρησής σας με τον δωρεάν διαδραστικό μας χάρτη.", "headerTitle": "Εκτιμήστε την κυκλοφορία πεζών για την επιχείρησή σας. ΔΩΡΕΑΝ", "headerSubtitle": "Αναλύστε την κυκλοφορία πεζών και βρείτε την καλύτερη τοποθεσία για το κατάστημα, το εστιατόριο ή το γραφείο σας.", "loadingText": "Υπολογισμός κυκλοφορίας πεζών στην περιοχή...", "mapPlaceholder": "Φόρτωση χάρτη...", "peoplePassingBy": "Άνθρωποι που περνούν"},
    "cs": {"pageTitle": "Bezplatný Odhadovač Pěšího Provozu | Naplánujte Nové Umístění Vašeho Podniku", "metaDescription": "Odhadněte pěší provoz pro umístění vašeho podniku pomocí naší bezplatné interaktivní mapy.", "headerTitle": "Odhadněte pěší provoz pro váš podnik. ZDARMA", "headerSubtitle": "Analyzujte pěší provoz a najděte nejlepší umístění pro váš obchod, restauraci nebo kancelář.", "loadingText": "Výpočet pěšího provozu v oblasti...", "mapPlaceholder": "Načítání mapy...", "peoplePassingBy": "Lidé procházející kolem"},
    "hu": {"pageTitle": "Ingyenes Gyalogos Forgalom Becslő | Tervezze Meg Új Üzleti Helyét", "metaDescription": "Becslje meg a gyalogos forgalmat üzleti helyszíne számára ingyenes interaktív térképünkkel.", "headerTitle": "Becslje meg a gyalogos forgalmat üzlete számára. INGYEN", "headerSubtitle": "Elemezze a gyalogos forgalmat, és találja meg a legjobb helyet üzlete, étterme vagy irodája számára.", "loadingText": "A terület gyalogos forgalmának kiszámítása...", "mapPlaceholder": "Térkép betöltése...", "peoplePassingBy": "Elhaladó emberek"},
    "sv": {"pageTitle": "Gratis Fottrafikskalkylator | Planera Din Nya Affärslokation", "metaDescription": "Uppskatta fottrafiken för din affärslokation med vår gratis interaktiva karta.", "headerTitle": "Uppskatta fottrafik för ditt företag. GRATIS", "headerSubtitle": "Analysera fottrafiken och hitta den bästa platsen för din butik, restaurang eller kontor.", "loadingText": "Beräknar fottrafik i området...", "mapPlaceholder": "Laddar karta...", "peoplePassingBy": "Förbipasserande människor"},
    "he": {"pageTitle": "מחשבון תנועת רגליים חינמי | תכנן את מיקום העסק החדש שלך", "metaDescription": "הערך את תנועת הרגליים למיקום העסק שלך באמצעות המפה האינטראקטיבית החינמית שלנו.", "headerTitle": "הערך את תנועת הרגליים לעסק שלך. בחינם!", "headerSubtitle": "נתח את תנועת הרגליים ומצא את המיקום הטוב ביותר לחנות, מסעדה או משרד שלך.", "loadingText": "חישוב תנועת הרגליים באזור...", "mapPlaceholder": "טוען מפה...", "peoplePassingBy": "אנשים שעוברים"},
    "da": {"pageTitle": "Gratis Fodgængertrafik Estimator | Planlæg Din Nye Forretningslokation", "metaDescription": "Estimer fodgængertrafikken til din forretningslokation med vores gratis interaktive kort.", "headerTitle": "Estimer fodgængertrafik til din virksomhed. GRATIS", "headerSubtitle": "Analyser fodgængertrafikken og find den bedste placering til din butik, restaurant eller kontor.", "loadingText": "Beregner fodgængertrafik i området...", "mapPlaceholder": "Indlæser kort...", "peoplePassingBy": "Folk der går forbi"},
    "fi": {"pageTitle": "Ilmainen Jalankulkuliikenteen Arvioija | Suunnittele Uusi Liiketilasi Sijainti", "metaDescription": "Arvioi jalankulkuliikennettä liiketilasi sijainnille ilmaisella interaktiivisella kartallamme.", "headerTitle": "Arvioi jalankulkuliikennettä yrityksellesi. ILMAISEKSI", "headerSubtitle": "Analysoi jalankulkuliikennettä ja löydä paras sijainti kaupallesi, ravintolallesi tai toimistollesi.", "loadingText": "Lasketaan jalankulkuliikennettä alueella...", "mapPlaceholder": "Ladataan karttaa...", "peoplePassingBy": "Ohikulkijat"},
    "no": {"pageTitle": "Gratis Fottrafikkestimator | Planlegg Din Nye Forretningslokasjon", "metaDescription": "Estimer fottrafikken for din forretningslokasjon med vårt gratis interaktive kart.", "headerTitle": "Estimer fottrafikk for din bedrift. GRATIS", "headerSubtitle": "Analyser fottrafikken og finn den beste plasseringen for butikken, restauranten eller kontoret ditt.", "loadingText": "Beregner fottrafikk i området...", "mapPlaceholder": "Laster kart...", "peoplePassingBy": "Folk som går forbi"},
    "bg": {"pageTitle": "Безплатен Оценител на Пешеходния Трафик | Планирайте Новото си Бизнес Място", "metaDescription": "Оценете пешеходния трафик за местоположението на вашия бизнес с нашата безплатна интерактивна карта.", "headerTitle": "Оценете пешеходния трафик за вашия бизнес. БЕЗПЛАТНО", "headerSubtitle": "Анализирайте пешеходния трафик и намерете най-доброто място за вашия магазин, ресторант или офис.", "loadingText": "Изчисляване на пешеходния трафик в района...", "mapPlaceholder": "Зареждане на картата...", "peoplePassingBy": "Минаващи хора"},
    "sk": {"pageTitle": "Bezplatný Odhadovač Pešej Premávky | Naplánujte Nové Umiestnenie Vášho Podniku", "metaDescription": "Odhadnite pešiu premávku pre umiestnenie vášho podniku pomocí naší bezplatné interaktivní mapy.", "headerTitle": "Odhadnite pešiu premávku pre váš podnik. ZDARMA", "headerSubtitle": "Analyzujte pešiu premávku a nájdite najlepšie miesto pre váš obchod, reštauráciu alebo kanceláriu.", "loadingText": "Výpočet pešej premávky v oblasti...", "mapPlaceholder": "Načítavanie mapy...", "peoplePassingBy": "Prechádzajúci ľudia"},
    "hr": {"pageTitle": "Besplatni Procjenitelj Pješačkog Prometa | Planirajte Novu Lokaciju Svog Posla", "metaDescription": "Procijenite pješački promet za lokaciju vašeg poslovanja pomoću naše besplatne interaktivne karte.", "headerTitle": "Procijenite pješački promet za vaš posao. BESPLATNO", "headerSubtitle": "Analizirajte pješački promet i pronađite najbolju lokaciju za svoju trgovinu, restoran ili ured.", "loadingText": "Izračunavanje pješačkog prometa u području...", "mapPlaceholder": "Učitavanje karte...", "peoplePassingBy": "Ljudi koji prolaze"},
    "sr": {"pageTitle": "Бесплатни Процењивач Пешачког Саобраћаја | Планирајте Нову Локацију Свог Посла", "metaDescription": "Процените пешачки саобраћај за локацију вашег посла помоћу наше бесплатне интерактивне мапе.", "headerTitle": "Процените пешачки саобраћај за ваш посао. БЕСПЛАТНО", "headerSubtitle": "Анализирајте пешачки саобраћај и пронађите најбољу локацију за вашу продавницу, ресторан или канцеларију.", "loadingText": "Израчунавање пешачког саобраћаја у области...", "mapPlaceholder": "Учитавање мапе...", "peoplePassingBy": "Људи који пролазе"},
    "lt": {"pageTitle": "Nemokamas Pėsčiųjų Eismo Vertintojas | Planuokite Naują Verslo Vietą", "metaDescription": "Įvertinkite pėsčiųjų eismą jūsų verslo vietai naudodami mūsų nemokamą interaktyvų žemėlapį.", "headerTitle": "Įvertinkite pėsčiųjų eismą savo verslui. NEMOKAMAI", "headerSubtitle": "Analizuokite pėsčiųjų eismą ir raskite geriausią vietą savo parduotuvei, restoranui ar biurui.", "loadingText": "Skaičiuojamas pėsčiųjų eismas rajone...", "mapPlaceholder": "Kraunamas žemėlapis...", "peoplePassingBy": "Praeinantys žmonės"},
    "sl": {"pageTitle": "Brezplačni Ocenjevalec Peš Prometa | Načrtujte Novo Lokacijo Vašega Posla", "metaDescription": "Ocenite peš promet za lokacijo vašega poslovanja z našim brezplačnim interaktivnim zemljevidom.", "headerTitle": "Ocenite peš promet za vaš posel. BREZPLAČNO", "headerSubtitle": "Analizirajte peš promet in poiščite najboljšo lokacijo za vašo trgovino, restavracijo ali pisarno.", "loadingText": "Izračunavanje peš prometa na območju...", "mapPlaceholder": "Nalaganje zemljevida...", "peoplePassingBy": "Mimo hodijo ljudje"},
    "lv": {"pageTitle": "Bezmaksas Gājēju Plūsmas Novērtētājs | Plānojiet Jaunu Biznesa Vietu", "metaDescription": "Novērtējiet gājēju plūsmu jūsu biznesa vietai, izmantojot mūsu bezmaksas interaktīvo karti.", "headerTitle": "Novērtējiet gājēju plūsmu savam biznesam. BEZ MAKSAS", "headerSubtitle": "Analizējiet gājēju plūsmu un atrodiet labāko vietu savam veikalam, restorānam vai birojam.", "loadingText": "Aprēķina gājēju plūsmu rajonā...", "mapPlaceholder": "Ielādē karti...", "peoplePassingBy": "Gājēji, kas iet garām"},
    "et": {"pageTitle": "Tasuta Jalakäijate Liikluse Hindaja | Planeerige Oma Uus Ärikoht", "metaDescription": "Hinnake jalakäijate liiklust oma ärikoha jaoks meie tasuta interaktiivse kaardi abil.", "headerTitle": "Hinnake jalakäijate liiklust oma ärile. TASUTA", "headerSubtitle": "Analüüsige jalakäijate liiklust ja leidke parim koht oma poele, restoranile või kontorile.", "loadingText": "Jalakäijate liikluse arvutamine piirkonnas...", "mapPlaceholder": "Kaardi laadimine...", "peoplePassingBy": "Möödujad"},
    "hy": {"pageTitle": "Հաշմանդամի անվճար գնահատող | Պլանավորեք Ձեր նոր բիզնեսի գտնվելու վայրը", "metaDescription": "Գնահատեք հետիոտնային երթևեկությունը Ձեր բիզնեսի գտնվելու վայրի համար՝ օգտագործելով մեր անվճար ինտերակտիվ քարտեզը:", "headerTitle": "Գնահատեք հետիոտնային երթևեկությունը Ձեր բիզնեսի համար: ԱՆՎՃԱՐ", "headerSubtitle": "Վերլուծեք հետիոտնային երթևեկությունը և գտեք լավագույն վայրը Ձեր խանութի, ռեստորանի կամ գրասենյակի համար:", "loadingText": "Հաշվարկվում է հետիոտնային երթևեկությունը տարածքում...", "mapPlaceholder": "Քարտեզը բեռնվում է...", "peoplePassingBy": "Անցնող մարդիկ"},
    "az": {"pageTitle": "Pulsuz Piyada Trafiki Təxminatçısı | Yeni Biznes Yerinizi Planlaşdırın", "metaDescription": "Pulsuz interaktiv xəritəmizdən istifadə edərək biznes yeriniz üçün piyada trafikini təxmin edin.", "headerTitle": "Biznesiniz üçün piyada trafikini təxmin edin. PULSUZ!", "headerSubtitle": "Piyada trafikini təhlil edin və mağazanız, restoranınız və ya ofisiniz üçün ən yaxşı yeri tapın.", "loadingText": "Ərazidə piyada trafiki hesablanır...", "mapPlaceholder": "Xəritə yüklənir...", "peoplePassingBy": "Keçən insanlar"},
    "ka": {"pageTitle": "უფასო ფეხით მოსიარულეთა ტრაფიკის შემფასებელი | დაგეგმეთ თქვენი ახალი ბიზნესის ადგილმდებარეობა", "metaDescription": "შეაფასეთ ფეხით მოსიარულეთა ტრაფიკი თქვენი ბიზნესის ადგილმდებარეობისთვის ჩვენი უფასო ინტერაქტიული რუკის გამოყენებით.", "headerTitle": "შეაფასეთ ფეხით მოსიარულეთა ტრაფიკი თქვენი ბიზნესისთვის. უფასოდ!", "headerSubtitle": "გაანალიზეთ ფეხით მოსიარულეთა ტრაფიკი და იპოვეთ საუკეთესო ადგილი თქვენი მაღაზიის, რესტორნის ან ოფისისთვის.", "loadingText": "ფეხით მოსიარულეთა ტრაფიკის გამოთვლა ზონაში...", "mapPlaceholder": "რუკის ჩატვირთვა...", "peoplePassingBy": "გამვლელები"},
    "sq": {"pageTitle": "Vlerësues Falas i Trafikut të Këmbësorëve | Planifikoni Vendndodhjen e Re të Biznesit Tuaj", "metaDescription": "Vlerësoni trafikun e këmbësorëve për vendndodhjen e biznesit tuaj duke përdorur hartën tonë interaktive falas.", "headerTitle": "Vlerësoni trafikun e këmbësorëve për biznesin tuaj. FALAS!", "headerSubtitle": "Analizoni trafikun e këmbësorëve dhe gjeni vendndodhjen më të mirë për dyqanin, restorantin ose zyrën tuaj.", "loadingText": "Po llogaritet trafiku i këmbësorëve në zonë...", "mapPlaceholder": "Duke ngarkuar hartën...", "peoplePassingBy": "Njerëz që kalojnë"},
    "mk": {"pageTitle": "Бесплатен Проценувач на Пешачки Сообраќај | Планирајте ја Новата Локација на Вашиот Бизнис", "metaDescription": "Проценете го пешачкиот сообраќај за локацијата на вашиот бизнис со нашата бесплатна интерактивна мапа.", "headerTitle": "Проценете го пешачкиот сообраќај за вашиот бизнис. БЕСПЛАТНО!", "headerSubtitle": "Анализирајте го пешачкиот сообраќај и пронајдете ја најдобрата локација за вашата продавница, ресторан или канцеларија.", "loadingText": "Се пресметува пешачкиот сообраќај во областа...", "mapPlaceholder": "Се вчитува мапата...", "peoplePassingBy": "Луѓе што поминуваат"},
    "bs": {"pageTitle": "Besplatni Procjenitelj Pješačkog Saobraćaja | Planirajte Novu Lokaciju Vašeg Posla", "metaDescription": "Procijenite pješački saobraćaj za lokaciju vašeg poslovanja pomoću naše besplatne interaktivne mape.", "headerTitle": "Procijenite pješački saobraćaj za vaš posao. BESPLATNO!", "headerSubtitle": "Analizirajte pješački saobraćaj i pronađite najbolju lokaciju za vašu prodavnicu, restoran ili kancelariju.", "loadingText": "Izračunavanje pješačkog saobraćaja u području...", "mapPlaceholder": "Učitavanje mape...", "peoplePassingBy": "Ljudi koji prolaze"},
    "mt": {"pageTitle": "Stimatur Bla Ħlas tat-Traffiku tal-Mixi | Ippjana l-Lokazzjoni l-Ġdida tan-Negozju Tiegħek", "metaDescription": "Stima t-traffiku tal-mixi għal-lokazzjoni tan-negozju tiegħek bl-użu tal-mappa interattiva bla ħlas tagħna.", "headerTitle": "Stima t-Traffiku tal-Mixi għan-Negozju Tiegħek. BLA ĦLAS!", "headerSubtitle": "Analizza t-traffiku tal-mixi u sib l-aħjar lokazzjoni għall-ħanut, ir-restorant jew l-uffiċċju tiegħek.", "loadingText": "Qed jiġi kkalkulat it-traffiku tal-mixi fiż-żona...", "mapPlaceholder": "Qed jittella’ l-mappa...", "peoplePassingBy": "Nies li jgħaddu"},
    "is": {"pageTitle": "Ókeypis Fótgangandi Umferðar Matstæki | Skipuleggðu Nýja Staðsetningu Fyrirtækis Þíns", "metaDescription": "Metið fótgangandi umferð fyrir staðsetningu fyrirtækis þíns með ókeypis gagnvirku korti okkar.", "headerTitle": "Metið fótgangandi umferð fyrir fyrirtækið þitt. ÓKEYPIS!", "headerSubtitle": "Greindu fótgangandi umferð og finndu bestu staðsetningu fyrir verslun þína, veitingastað eða skrifstofu.", "loadingText": "Reiknar fótgangandi umferð á svæðinu...", "mapPlaceholder": "Hleður korti...", "peoplePassingBy": "Fólk sem gengur framhjá"},
    "lb": {"pageTitle": "Gratis Foussgängertrafik Schätzer | Plangt Är Nei Geschäftsplaz", "metaDescription": "Schätzt de Foussgängertrafik fer Är Geschäftsplaz mat eiser gratis interaktiver Kaart.", "headerTitle": "Schätzt de Foussgängertrafik fer Äert Geschäft. GRATIS!", "headerSubtitle": "Analyséiert de Foussgängertrafik a fannt déi bescht Plaz fer Äre Buttek, Restaurant oder Büro.", "loadingText": "Berechnung vum Foussgängertrafik am Gebitt...", "mapPlaceholder": "Kaart lued...", "peoplePassingBy": "Leit déi vorbeigehen"},
    "fo": {"pageTitle": "Ókeypis Fótgangara Umferðar Matstæki | Skipulegg Fína Nýggja Staðseting Fyrirtækis Tíns", "metaDescription": "Mat fótgangara umferð fyri staðseting fyrirtækis tíns við ókeypis gagnvirkum korti okkara.", "headerTitle": "Mat fótgangara umferð fyri fyrirtæki títt. ÓKEYPIS!", "headerSubtitle": "Grein fótgangara umferð og finn besta staðseting fyri handil tín, matstovu ella skrivstovu.", "loadingText": "Útrokning av fótgangara umferð á økinum...", "mapPlaceholder": "Kortið verður loðið...", "peoplePassingBy": "Fólk sum gongur framvið"}
};

function setLanguage(lang) {
    let inUserLanguage = translations[lang] || translations["en"]
    
        document.getElementById("page-title").textContent =inUserLanguage.pageTitle;
        document.querySelector('meta[name="description"]').setAttribute("content", inUserLanguage.metaDescription);
        document.getElementById("title-block").querySelector("h1").textContent = inUserLanguage.headerTitle;
        document.getElementById("title-block").querySelector("p").textContent = inUserLanguage.headerSubtitle;
        document.getElementById("loading").textContent = inUserLanguage.loadingText;
        if (document.getElementById("map")) document.getElementById("map").setAttribute("data-placeholder", inUserLanguage.mapPlaceholder);
    
    return inUserLanguage;
}

const userLang = navigator.language.substring(0, 2);
if (translations[userLang]) {
    setLanguage(userLang);
}

export {setLanguage}